language: ruby
cache: bundler
rvm:
  - 2.3.3

script: bundle exec jekyll build && bundle exec htmlproofer ./_site --allow-hash-href

notifications:
  slack: ballroomdanceclub:YufnUV3hTqwD4sNIoDGLoTE5
