language: ruby
cache: bundler
rvm:
  - 2.7.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --allow-hash-href

notifications:
  slack: ballroomdanceclub:YufnUV3hTqwD4sNIoDGLoTE5
  email: false
