github_username:  ballroom-dance-club
repository: ballroom-dance-club/ballroom-dance-club.github.io

permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude: ['vendor', 'README.md', 'Gemfile*', 'CNAME']

title: The Ballroom Dance Club

description: >
  The Ballroom Dance Club is an organization in Ann Arbor, Michigan
  focused on learning ballroom, Latin, and social dances for fun!

logo: /images/logos/the-ballroom-dance-club-logo.png

facebook:
    publisher: https://www.facebook.com/UMBDC

social:
  links:
    - https://www.facebook.com/UMBDC

google_analytics_id: UA-28330237-1

timezone: America/Detroit

domain: https://ballroomdance.club

sitewide_info_message:
sitewide_warning_message:

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/logos/the-ballroom-dance-club-logo.png
        height: 501
        width: 512
