github_username:  ballroom-dance-club
repository: ballroom-dance-club/ballroom-dance-club.github.io

permalink: pretty
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude: [vendor]

title: The Ballroom Dance Club

description: >
  The Ballroom Dance Club is an organization in Ann Arbor, Michigan
  focused on learning ballroom, Latin, and social dances for fun!

facebook:
  publisher: https://www.facebook.com/UMBDC

social:
  links:
    - https://www.facebook.com/UMBDC

timezone: America/Detroit

domain: http://ballroomdance.club
