url: "http://ballroomclubum.com"
github_username:  ballroom-dance-club
repository: ballroom-dance-club/ballroom-dance-club.github.io

permalink: pretty
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
